version: "3.8"

services:
  metadata_reader:
    build:
      context: .
      dockerfile: Dockerfile.MetadataReader
    ports:
      - "8002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    restart: on-failure
    
  pools:
    build:
      context: .
      dockerfile: Dockerfile.Pools
    ports:
      - "8003:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - metadata_reader
    restart: on-failure
    
  rewards:
    build:
      context: .
      dockerfile: Dockerfile.Rewards
    ports:
      - "8004:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    depends_on:
      - metadata_reader
    restart: on-failure
